# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9783e9690b9ae8c9db3bb0a64fdef6f93af4198ed01468c6b0d16f7572a05f1d600d22268ae127c35a99d202a008d8c2cc9e025ffbc5f9f2e911958cd8559528

test:
  secret_key_base: 25733060a922ee87d0ae77355e30eda518dda76bc328fda24133f9ae49cb9146ac72291290cac5ba16ca244636b3fc232769a62068980393465fdceac1cda97d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
